### ISSUE TITLE
Identical entries in the changelog are not repeated

### ISSUE THREAD

**Issue by emdv88** [ICTU/quality-time#2893] opened 2021-11-18 12:38 UTC
When there are multiple identical entries in the changelog, only the last one will be shown. This seems to be consistent in all changelogs.

### Steps to reproduce: 
* go to a report
* add one subject
* add a metric to that subject
* delete that subject
* add another subject

### expected changelog:
* previous changes
* subject added
* metric added
* subject deleted
* subject added

### actual changelog:
* previous changes
* metric added
* subject deleted
* subject added

**Comment by fniessink** [comment] 2021-11-19 16:59
This is caused by this code in `components/server/src/database/reports.py` (line 140-141):

```python
    # Weed out potential duplicates, because when a user moves items between reports both reports get the same delta
    return list(unique(changes, lambda change: cast(dict[str, str], change["delta"])["description"]))[:nr_changes]
```

This obviously weeds out too many deltas. 

One way to solve this would be to give all deltas a guid. In case of moving items from one report to another report, the two deltas would need to get the same guid so one would still be weeded from the list.

Another way to solve this would be to make sure the second argument to `unique` (`get_key`) takes into account the guid of the items involved in the change.

**Closed as completed** 2021-11-21 16:51 UTC
