### ISSUE TITLE
New metric for job duration

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#7410] opened 2023-11-03 11:09 UTC
**Is your feature request related to a problem? Please describe.**
Development teams sometimes have issue with the length of certain jobs (build steps) in their pipeline, like the automated regression test (ART). Teams have a need for monitoring the length of jobs so that they can take action when these jobs take too much time. Currently, there is no way of doing this because there is no metric for this.

**Describe the solution you'd like**
A new metric that measures the running time of a job (build step) and uses the pipelines (Jenkins, GitLab, GitHub) as a source.

**Describe alternatives you've considered**
Alternatively, the metric 'performance test duration' and create a fake JMeter CSV as a report.

<img width="111" alt="MicrosoftTeams-image" src="https://github.com/ICTU/quality-time/assets/95095453/73803590-0926-49f6-8cfc-8735cb4f24d8">

**Comment by fniessink** [comment] 2023-11-15 14:38
Duplicate of #6423

**Closed as completed by fniessink** 2023-11-15 14:38 UTC
Labels: Metric(s)
