### ISSUE TITLE
Issue Identifier value disappears

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#3559] opened 2022-03-17 12:17 UTC
Currently, there are a few issues with the Issue Identifier, the field where the user can link metrics to one or more issues from the issue tracker.
![image](https://user-images.githubusercontent.com/95095453/152191476-c2cad3b9-03b3-47da-a91a-bf097630a1cb.png)

Issues:
- When a value is entered and the user waits, the value disappears after a while. This is not useful and gives the user too little time to think.

**Comment by Sebastiaan127001** [comment] 2022-03-17 12:17
https://github.com/ICTU/quality-time/issues/3367

**Comment by fniessink** [comment] 2022-03-22 11:56
This probably happens when new measurements arrive from the server and React redraws the components, however I can't reproduce this currently with the latest release candidate.

**Comment by Sebastiaan127001** [comment] 2023-01-24 09:39
@fniessink if I remember correctly, we have discussed this bug recently. I believe this one is a duplicate now and can be removed, do you agree?

**Comment by fniessink** [comment] 2023-01-24 12:03
I haven't seen this problem anymore either, so closing this issue.

**Closed as completed by fniessink** 2023-01-24 12:03 UTC
