### ISSUE TITLE
PDF report contains configuration items

### ISSUE THREAD

**Issue by denniebouman** [ICTU/quality-time#8057] opened 2024-02-09 10:43 UTC
**Describe the bug**
PDF report contains configuration items. E.g. Configuration, Desired reaction times, Report title, Report subtitle, etc.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on 'Download report as PDF'
3. See configuration items as first entry in report

**Expected behaviour**
Configuration items not present in report

**Your environment (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Quality-time version: v5.7.0

**Comment by fniessink** [comment] 2024-02-09 11:35
Duplicate of #8054.

**Closed as completed by fniessink** 2024-02-09 11:35 UTC
