### ISSUE TITLE
Cannot parse artefacts of latest version of OWASP dependency-check (9.0.4)

### ISSUE THREAD

**Issue by Sebastiaan127001** [ICTU/quality-time#7657] opened 2023-12-13 07:59 UTC
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Your environment (please complete the following information):**
 - OS: [e.g. Linux]
 - Browser [e.g. Chrome, Safari]
 - Quality-time version [e.g. v4.0.0]

**Additional context**

**Comment by fniessink** [comment] 2023-12-13 08:29
Duplicate of #7655.

**Closed as completed by fniessink** 2023-12-13 08:29 UTC
